### ISSUE TITLE
Drop Python 2 support and test against Zope 5

### ISSUE THREAD

**Issue by icemac** [zopefoundation/AccessControl#106]
Version 5.0 is not intended to be used together with Zope 4 as it removes DeprecationWarnings which have to be resolved to smoothly migrate to Zope 5.

Currently we are testing against the versions pinned for Zope 4 because we still support Python 2.

To clean this up Python 2 support should be dropped (I see no problem here as AccessControl is not a low level package but cannot be used outside Zope) and we should extend the versions pinned on master in buildout.cfg.

Additionally Python 3.5 support can be dropped, as it is no longer needed for Zope 5.

**Comment by jugmac00** [comment]
> I see no problem here as ZCatalog is not a low level package but cannot be used outside Zope

Why do you mention ZCatalog? It is working on Python 3 right now.

**Comment by dataflake** [comment]
I guess this is OK but let me say again: I hope this is not starting a large wave of package conversions to "Python 3 only" just because "we can". Any package that drops Zope 4 compatibility requires two active development branches and two separate releases until we abandon Zope 4.

**Comment by icemac** [comment]
> > I see no problem here as ZCatalog is not a low level package but cannot be used outside Zope
> 
> Why do you mention ZCatalog? It is working on Python 3 right now.

I copied the issue text from a similar issue in ZCatalog, without reading the text again.

**Comment by icemac** [comment]
> I guess this is OK but let me say again: I hope this is not starting a large wave of package conversions to "Python 3 only" just because "we can". Any package that drops Zope 4 compatibility requires two active development branches and two separate releases until we abandon Zope 4.

This issues does not propose to drop Python 2 support because we can but because we have to in order to test the package against the dependencies used in Zope 5. As we use Python-3-only dependencies there the tests will fail on Python 2.

The roadmap says that Zope 4 is in bugfix mode until end of 2021. We already have to maintain two branches because we dropped deprecation warnings. Using the new AccessControl in Zope 4 could break things for users who did not already fix their deprecation warnings. I am going to create a branch for Zope 4 and to update Zope 4 to use this branch when doing checkouts. (Same for the other Zope 5 only packages.)

**Comment by dataflake** [comment]
If there's good reason for moving to "Zope 5/Python 3" only then I fully agree with you. I know I sound like a broken record on this.

**Comment by icemac** [comment]
Fixed by #137.
