### ISSUE TITLE
Use .meta.toml for configuration

### ISSUE THREAD

**Issue by icemac** [zopefoundation/AccessControl#117]
Currently a manual configuration approach is used. This is enough for now.
To be able to get upcoming changes `.meta.toml` should be used.

**Comment by dataflake** [comment]
Among other things, the `PURE_PYTHON` mode must be implemented here first. Currently the implementation is chosen by calling a function. And even if the python implementation is selected, there are some imports from C modules.

**Comment by dataflake** [comment]
Additionally, the `.manylinux-install.sh` file wants to also compile wheels for Python 3.10. This fails here because at least one dependency, `RestrictedPython`, is configured to explicitly declare non-compatibility with Python 3.10 and so the dependency cannot be loaded from PyPI.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2021-8-1 00:21 -0700:
>Among other things, the `PURE_PYTHON` mode must be implemented here first. Currently the implementation is chosen by calling a function. And even if the python implementation is selected, there are some imports from C modules.

In general the implementation should be determined by configuration.
This means that `PURE_PYTHON` should only determine the
"default implementation" (mainly used for the tests).

In branch `ExtensionClass_Base_as_object`, I have
implemented that `AccessControl` automatically falls back
to the Python implementation if the C implementation is not
available.
