### ISSUE TITLE
ModuleSecurityInfo('os').declarePublic('environ') allows os.system

### ISSUE THREAD

**Issue by stephan-hof** [zopefoundation/AccessControl#12]
as mentioned above I have the following line in one of my zope Products.
```python
ModuleSecurityInfo('os').declarePublic('environ')
```

Unfortunately in a PythonScript inside Zope, which should run under restricted python, I write code like this without getting an Unauthorized exception. Instead the os.system is happily executed, giving a lot of 'fun' to the users of my system :)
```python
import os
os.system('ls /')
```

I looked a bit through the code and the following function in SecurityInfo.py got my attention.
```python
class _ModuleSecurityInfo(SecurityInfo):
    """Encapsulate security information for modules."""

    __call____roles__ = ACCESS_PRIVATE
    def __call__(self, name, value):
        """Callback for __allow_access_to_unprotected_subobjects__ hook."""
        access = self.names.get(name, _marker)
        if access is not _marker:
            return access == ACCESS_PUBLIC
        return getattr(self, 'access', 0)
```
The interesting line is ```getattr(self, 'access', 0)```.  Somehow self takes part in acquisition with the os module as parent.

```
print Acquisition.aq_chain(self) 
[<AccessControl.SecurityInfo._ModuleSecurityInfo object at 0xa25c28c>, <module 'os' from '/usr/lib/python2.7/os.pyc'>]
```
So, self having no attribute 'access', Acquisition jumps back to the os module which has an attribute being [os.access](https://docs.python.org/release/2.7.11/library/os.html#os.access)

Access control evaluates [os.access](https://docs.python.org/release/2.7.11/library/os.html#os.access) as True which means 'system' is allowed.

I don't have a big clue how AccessControl works, so its hard for me to say what is the 'appropriate' fix for this. Right now I changed the the ``__call__`` method to this:
```
    __call____roles__ = ACCESS_PRIVATE
    def __call__(self, name, value):
        """Callback for __allow_access_to_unprotected_subobjects__ hook."""
        access = self.names.get(name, _marker)
        if access is not _marker:
            return access == ACCESS_PUBLIC

        me = Acquisition.aq_base(self)
        return getattr(me, 'access', 0)
```

**Comment by tseaver** [comment]
Thank you for the report!  I believe your analysis is correct, and that acquiring `access` cannot be intended.  Rather than use `aq_base`, I propose that we update `SecurityInfo` such that it sets `access` to False by default at the class level.  I will test this change with a full Zope instance to ensure it doesn't break stuff.

**Comment by stephan-hof** [comment]
Hi,

I'll will  apply your proposed change also to my Zope instance and let you know if something breaks.

**Comment by tseaver** [comment]
After checking:  Setting `access = False` in the `SecurityInfo` base class causes tests to fail (and likely breaks a bunch of stuff).  Setting it in the derived `_ModuleSecurityInfo` class lets them all pass, but should still fix your issue.

**Comment by tseaver** [comment]
via e47723efe382315358909e4773770bb4a522868d
