### ISSUE TITLE
Race condition in secureModule

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/AccessControl#123]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

In a Zope environment that includes `Products.PythonScripts` which use `import`, we sometimes see the following error message right after startup of an instance:
```
...
    Module AccessControl.ZopeGuards, line 422, in guarded_import
    Module AccessControl.ZopeGuards, line 483, in load_module
    Module AccessControl.SecurityInfo, line 273, in secureModule

KeyError: 'perfact.zodbsync'
```
As far as I understand, this is a race condition when multiple requests run into the same initializing script which imports the same library. They land on different threads of the same Zope instance, and all of them execute the following code snippet from `SecurityInfo.py`:

```
    modsec = _moduleSecurity.get(mname, None)
    if modsec is None:
        if mname in _appliedModuleSecurity:
            return sys.modules[mname]
        return  # no MSI, no module

    if imp:
        __import__(mname, *imp)
    del _moduleSecurity[mname]
```
That is, both threads try to import the module, add it to `_moduleSecurity` and both threads try to execute the `del` statement, but only one of them succeds.

Not sure how to fix this, maybe a simple wrapping with `try except`?
### What I did:
Installed Zope 5.4 with `Products.PythonScripts` and added a script that imports a module. Started the instance, which by default starts four threads, and run two simultaneous requests that both target the script.

### What I expect to happen:
Both requests should finish independently.

### What actually happened:
One of them fails with the above traceback.

### What version of Python and Zope/Addons I am using:
Zope 5.4, Products.PythonScripts 4.13

**Comment by d-maurer** [comment]
Viktor Dick wrote at 2022-3-25 08:09 -0700:
> ...
>As far as I understand, this is a race condition when multiple requests run into the same initializing script which imports the same library. They land on different threads of the same Zope instance, and all of them execute the following code snippet from `SecurityInfo.py`:
>
>```
>    modsec = _moduleSecurity.get(mname, None)
>    if modsec is None:
>        if mname in _appliedModuleSecurity:
>            return sys.modules[mname]
>        return  # no MSI, no module
>
>    if imp:
>        __import__(mname, *imp)
>    del _moduleSecurity[mname]
>```
>That is, both threads try to import the module, add it to `_moduleSecurity` and both threads try to execute the `del` statement, but only one of them succeds.
>
>Not sure how to fix this, maybe a simple wrapping with `try except`?

Yes: `try: ... except KeyError: pass`

Are you a Zope contributor?
If not, are you ready to become one?
Then you could fix this bug yourself.

**Comment by viktordick** [comment]
Yes, I am and can do it. I was simply unsure if this is the right fix or if we need some more elaborate mutex or something like that. But I guess this should be enough.

**Comment by viktordick** [comment]
Yes, that's why it takes more than 5 minutes ;) Almost ready.
