### ISSUE TITLE
Remove deprecated features and imports in version 5

### ISSUE THREAD

**Issue by sallner** [zopefoundation/AccessControl#32]
There are modules which are deprecated since they have been moved into the repository 7 years ago. They should be cleaned up and the respective tests should be adapted.

- [x]  AccessControl/Owned.py
- [x]  AccessControl/Role.py
- [x]  AccessControl/User.py
- [x]  AccessControl/DTML.py
- [x] AccessControl/Permissions.py

**Comment by dataflake** [comment]
Unfortunately none of those deprecated imports contained any hint of when the code will be removed. In 22bd20ead14ed37df2d4d80f353d39589f2626f6 I have added that hint and set AccessControl version 5 as the target version for those removals. I have also removed this issue from the TODO list for Zope 4.

**Comment by icemac** [comment]
@dataflake Thank you for improving the deprecation warnings. I added this issue to the Zope 5 TODO list.

**Comment by icemac** [comment]
Fixed in #103
