### ISSUE TITLE
Bogus warning: inherited methods are not "nonexistent" 

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/AccessControl#49]
E.g.: https://github.com/zopefoundation/Products.PythonScripts/issues/13

Subclasses should be free to remap the permissions of base class methods without adding a shim:  in fact, `OFS.History.Historical.manage_historyCopy` is *designed* that way.

**Comment by icemac** [comment]
Currently `Products.CMFCore.PortalContent.PortalContent` provokes warning about missing `manage_FTPstat`.

**Comment by icemac** [comment]
But the method does not exist, so it is correct that `AccessControl` complains.
In the `Products.PythonScripts` the methods were also not existing because they were removed in Zope 4.0a2. So I do not see that this problem exists for inherited methods.
