### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by tomgross** [zopefoundation/AccessControl#8]
This should be ported to Python 3(.4) to allow to run Zope2 on Python 3.

**Comment by icemac** [comment]
ExtensionClass/ExtensionClass.h has untestted C code which uses ``Py_TPFLAGS_HAVE_CLASS`` which no longer exists in Python 3 but is needed by AccessControl

Possible fix (?) from https://github.com/encukou/py3c/blob/master/include/py3c/tpflags.h:

```

#if PY_MAJOR_VERSION >= 3 
#define Py_TPFLAGS_HAVE_CLASS 0 
#endif 

```

see ``py3`` branch which started working towards Python 3 compatibility.

**Comment by dwt** [comment]
Please see https://github.com/zopefoundation/AccessControl/pull/21 for the porting work.

**Comment by dwt** [comment]
While porting, we stumbled across this bug: https://github.com/zopefoundation/Acquisition/issues/9 which makes AccessControll tests fail on python 2.7. To us at the Sprint in Halle, the result was that we probably cannot support the pure python implementation of AccessControl and Persistence on python3.

**Comment by loechel** [comment]
which would be the best branch to set next steps on? I want to resolve the RestrictedPython update Path

**Comment by hannosch** [comment]
@loechel We have an open PR (#21) which is using the `py3-pure-python` branch. That's the current WIP.

**Comment by loechel** [comment]
thanks @hannosch

**Comment by hannosch** [comment]
With #21 merged, most of the work here is done.

What's missing is porting the C extension to Python 3. This requires updating the header files in `include/` to their latest version and changing `setup.py` to not skip the extension. With those changes the C extension fails to compile or segfaults even under Python 2.7. So there's work to be done here.

**Comment by tseaver** [comment]
@hannosch Maybe I could sit with you tomorrow during the sprint to work on getting the C extension working under Py3k.

**Comment by sallner** [comment]
We have a valid port and alpha release for the Python implementation so I think we can close this issue. For the port of the C implementation I opened a new one (#36).
