### ISSUE TITLE
AppVeyor does not run any tests

### ISSUE THREAD

**Issue by icemac** [zopefoundation/AccessControl#81]
It tries to run them using `python setup.py test -q` which is no longer supported.

**Comment by dataflake** [comment]
FYI, I had tried to use the `appveyor.yml` style used in the Zope repository, but that would always fail because it ended up attempting to run `tox` in each environment non as `<ENV>/bin/tox.exe` but as `<ENV>/bin/Scripts/tox.exe`. No idea what's happening there,

**Comment by icemac** [comment]
For reference: Commits made by @dataflake while woking on this issue:

* 172ade6
* cb0e71d
* c0384c3
