### ISSUE TITLE
Missing attribute check or value verification in owner.py

### ISSUE THREAD

**Issue by 1letter** [zopefoundation/AccessControl#91]
the method produced an error in some cases, e.g.[here](https://github.com/collective/collective.themefragments/issues/8)

it's to optimistic to use the `db` variable without a check. it can be `None`.

```
def ownerInfo(user, getattr=getattr):
    if user is None:
        return None
    uid = user.getId()
    if uid is None:
        return uid
    db = aq_parent(aq_inner(user))
    path = [absattr(db.id)]
    root = db.getPhysicalRoot()
    while 1:
        db = getattr(db, 'aq_inner', None)
        if db is None:
            break
        db = aq_parent(db)
        if db is root:
            break
        id = db.id
        if not isinstance(id, str):
            try:
                id = id()
            except:
                id = str(id)
        path.append(id)

    path.reverse()
```
thats my patch:
```
def ownerInfo(user, getattr=getattr):
    if user is None:
        return None
    uid = user.getId()
    if uid is None:
        return uid
    db = aq_parent(aq_inner(user))
    if not db:
        return None    
    path = [absattr(db.id)]
    root = db.getPhysicalRoot()
    while 1:
        db = getattr(db, 'aq_inner', None)
        if db is None:
            break
        db = aq_parent(db)
        if db is root:
            break
        id = db.id
        if not isinstance(id, str):
            try:
                id = id()
            except:
                id = str(id)
        path.append(id)

    path.reverse()
```

**Comment by d-maurer** [comment]
1letter wrote at 2019-11-22 00:21 -0800:
>the method produced an error in some cases, e.g.[here](https://github.com/collective/collective.themefragments/issues/8)
>
>it's to optimistic to use the `db` variable without a check. it can be `None`.

`AccessControl` used to be part of Zope and was only recently
made into an independent package.

In Zope, typical users come from a `UserFolder` and have it as
their acquisition container. That's what the `db` variable gets
as value.

In Zope, there have been a few special users which do not come
from a `UserFolder`. Apparently, `ownerInfo` was never called
for such users.

**Comment by 1letter** [comment]
I can't create a branch with a fix here. but i have signed contributor’s agreement for plone last year. can anyone give access, please?

**Comment by jugmac00** [comment]
@1letter Afaik you have to sign the same contributor agreement - but this time you have to enter **Zope** instead of **Plone**.

see here
https://community.plone.org/t/becoming-a-contributor-updated-version/8550

**Comment by 1letter** [comment]
thanks, i will do it.
