### ISSUE TITLE
Unwanted rollback of issue #35 fix

### ISSUE THREAD

**Issue by mpeeters** [zopefoundation/AccessControl#94]
The commit https://github.com/zopefoundation/AccessControl/commit/87e0d293ed8173b9f51ddd6620ff969fcf3fc68b#diff-98cd54ebe14a720c0cd69d62c00fc656 that solves the issue #35 was removed by Flake 8 fix commit https://github.com/zopefoundation/AccessControl/commit/36f630956e92d2bc92553962a99496c61f6d9c25#diff-98cd54ebe14a720c0cd69d62c00fc656

Can we agree that this line should be added again (with noqa comment) ? @pbauer @hannosch

**Comment by dataflake** [comment]
Fixed in 73cecf10fc644eb62a8d27a9493458764c3a8972
